### ISSUE TITLE
cannot run ftp on camera

### ISSUE THREAD

**Issue by schneemaier** [biemster/xm510-utils#1]
Hi, i am trying to figure out what i am doing wrong. I followed the instructions and now i have the ftp binary on the camera, However when i try to run it i get an error:
`/bin # ftp
-/bin/sh: ftp: not found
`
I think the binary has the correct permissions:
/bin # ls -l
total 446
....
-rwxrwxr-x    1 1000     232           5268 Dec 31  1969 ftp
...
-rwxr-xr-x    1 1000     232          55300 Dec 31  1969 ipc_chip_info

I also have ipc_chip_info added to the firmware and it works fine:
/bin # ipc_chip_info
---
chip:
  vendor: Xiongmai
  model: XM510
ethernet:
  mac: "00:12:16:a3:xx:xx"
rom:
  - type: nor
    size: 8M
    block: 64K
    partitions:
      - name: boot
        size: 0x40000
      - name: romfs
        size: 0x370000
      - name: user
        size: 0x280000
      - name: web
        size: 0x140000
      - name: custom
        size: 0x40000
      - name: mtd
        size: 0x50000
sensors:
  - vendor: Silicon Optronics
    model: JXH42
    control:
      bus: 0
      type: i2c
/bin # 

Thanks

**Comment by biemster** [comment]
I've changed the clib from static musl to dynamic uclib in commit 3288d73, since that worked on my camera. Could you try to compile with static musl by reverting this change in your local workdir?

**Comment by biemster** [comment]
Also, in the mean time I found a way more capable firmware (with proper ftp client) for my xm510 came here:
https://zftlab.org/pages/2018010700.html

So I kind of stopped using this ftp solution altogether, but have a look if my suggestion above works for you.

**Comment by schneemaier** [comment]
Thanks for the answer. I will try now both compiler on my camera.

Also thanks for the link of zftlab.org. It looks really interesting.

**Comment by schneemaier** [comment]
DId you see this project: https://github.com/OpenIPC/openipc-2.1 They are planning xm510 support, though it is not working yet

**Comment by biemster** [comment]
Very interesting indeed, I've been following their progress in the Telegram group for a while (where they just announced they will stop providing public downloads?)
